#!/bin/bash
yt="https://www.youtube.com/watch?v="
echo "$(<asciiart)"
while [ 1 ]
	do
	xsel -b > 'ytube'.txt
	url="$(<ytube.txt)"
	prev="$(<prev.txt)"
	sleep 1
	if [[ $url == *"$yt"* ]]
		then
			if [[ $prev != $url ]]
				then
					echo "Starting Download Now!"
					
					nohup xterm -hold -e "sh ydagent.sh" &> /dev/null & disown
					
					cp ytube.txt prev.txt
			fi
	fi
done
